print("Olá, Mundo")
print("Meu texto aqui")
print("Faz o L")
print("Bora Bill")
print("Eu gosto é assim amostradinho")
print("Lá ele")
print("Eu i casca di bala")
print("Ele gosta")
print("Que isso meu filho calma")
print("TOME")